version: '3'

services:
  postgres_farm:
    container_name: farm_db
    image: bitnami/postgresql:15.4.0
    ports:
      - '5678:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: farm
    volumes:
      - /postgres:/var/lib/postgresql/data
    networks:
      - net


  bot:
    container_name: farm_bot
    build: .
    environment:
      DBURL: jdbc:postgresql://farm_db:5678/
      DBUSER: admin
      DBNAME: farm
      DBPASSWORD: *
      BOT_TOKEN: *
      CREATOR_ID: *
    networks:
      - net

networks:
  net:
    driver: bridge